### PR TITLE
Add documentation for Typescript and resolve typing issues

### LINKED ISSUE #116: Add typescript example to the readme
Currently there are questions as to how the typescript integration works and so adding an example should clear that up for people interested in using typescript for their projects.

### LINKED ISSUE #117: Issues with the `P5Instance` interface
## Expected Behavior

All `p5` methods are exposed as part of the `P5Instance` interface.

## Actual Behavior

Inside the project [source code](https://github.com/jamesrweb/react-p5-wrapper/blob/master/src/index.tsx) everything works as expected, tests pass, etc.

During compilation however there seems to be some issue happening because when the project is utilised with typescript, the `P5Instance` interface doesn't seem to recognise the `p5` standard methods as it should since `P5Instance` extends `p5`.

I have a suspicion that this is because `p5` exposes a class, an interface and a namespace which all have the name `p5` and maybe this is causing the issue but I could be wrong about this assumption.

## Steps to Reproduce the Problem

This is the sketch I used to identify the issue:

```typescript
import React, { useState, useEffect } from "react";
import { P5Instance, ReactP5Wrapper } from "react-p5-wrapper";

function sketch(p5: P5Instance) {
  let rotation = 0;

  p5.setup = () => p5.createCanvas(600, 400, p5.WEBGL);

  p5.updateWithProps = props => {
    if (props.rotation) {
      rotation = (props.rotation * Math.PI) / 180;
    }
  };

  p5.draw = () => {
    p5.background(100);
    p5.normalMaterial();
    p5.noStroke();
    p5.push();
    p5.rotateY(rotation);
    p5.box(100);
    p5.pop();
  };
}

export default function App() {
  const [rotation, setRotation] = useState(0);

  useEffect(() => {
    const interval = setInterval(
      () => setRotation(rotation => rotation + 100),
      100
    );

    return () => {
      clearInterval(interval);
    };
  }, []);

  return <ReactP5Wrapper sketch={sketch} rotation={rotation} />;
}
```

As you can see `updateWithProps` is correctly identified but the other standard `p5` methods / constants don't seem to be recognised for some reason and show errors when compiled.

Also tested with the a sketch constant utilising the `Sketch` type but the same issue is apparent since the `p5` value is a `P5Instance` also in this case, usage of that can be seen below:

```ts
import React, { useState, useEffect } from "react";
import { ReactP5Wrapper, Sketch } from "react-p5-wrapper";

const sketch: Sketch = p5 => {
  let rotation = 0;

  p5.setup = () => p5.createCanvas(600, 400, p5.WEBGL);

  p5.updateWithProps = props => {
    if (props.rotation) {
      rotation = (props.rotation * Math.PI) / 180;
    }
  };

  p5.draw = () => {
    p5.background(100);
    p5.normalMaterial();
    p5.noStroke();
    p5.push();
    p5.rotateY(rotation);
    p5.box(100);
    p5.pop();
  };
}

export default function App() {
  const [rotation, setRotation] = useState(0);

  useEffect(() => {
    const interval = setInterval(
      () => setRotation(rotation => rotation + 100),
      100
    );

    return () => {
      clearInterval(interval);
    };
  }, []);

  return <ReactP5Wrapper sketch={sketch} rotation={rotation} />;
}
```

## Specifications

Package Version: >= 3.0.0

## Additional Comments

Perhaps it is my typescript config that is the issue, to double check the validity of this, can you try to reproduce locally also @yevdyko? If this is reproducible, I will look into this issue ASAP.

### PR DESCRIPTION
**Pull request by jamesrweb**
Fixes issue #116
Fixes issue #117

## Proposed Changes

- Require `@types/p5` as a dependency and not just on development (Should resolve #117)
- Add typescript documentation for the `P5Instance` and `Sketch` types. (Resolves #116)

### CODE REVIEW

**Comment by jamesrweb** [comment]
@yevdyko created this PR, didn't want to release without a second eye checking it resolves things as expected, can you review?

**Review by yevdyko — CHANGES_REQUESTED** [review]
Thanks for adding detailed examples!

I found them very useful and easy to follow, but I have doubts that Typescript types should be a part of the package as a dependency as they will be used not by everyone.

How about mentioning in the README for the Typescript examples that you should add `@types/p5` to your project as a dependency if you want to benefit from them?

**Comment by jamesrweb** [comment]
> Thanks for adding detailed examples!
> 
> 
> 
> I found them very useful and easy to follow, but I have doubts that Typescript types should be a part of the package as a dependency as they will be used not by everyone.
> 
> 
> 
> How about mentioning in the README for the Typescript examples that you should add `@types/p5` to your project as a dependency if you want to benefit from them?

@yevdyko since this package is tree shakeable since the latest major version, anything unused won't end up in the final build anyway and the types are helpful for JS users too since they will allow correct type hints within their code editor even if they opt not to use Typescript. What do you think about this though?

**Comment by jamesrweb** [comment]
How did your local tests go? Did everything look good on your end with the changes here in TS / JS?

**Comment by yevdyko** [comment]
@jamesrweb Sorry, I won't be able to test locally today :(

**Review by yevdyko — APPROVED** [review]
@jamesrweb Okie, let's release it that way!

🚀

**Comment by jamesrweb** [comment]
> @jamesrweb Sorry, I won't be able to test locally today :(

@yevdyko Could you do it tomorrow then? I don't want to release without a second eye testing.

**Comment by yevdyko** [comment]
@jamesrweb I've tested both types of examples: JS and TypeScript in `create-react-app` based applications. Everything works as expected.

image

**Comment by jamesrweb** [comment]
> @jamesrweb I've tested both types of examples: JS and TypeScript in `create-react-app` based applications. Everything works as expected.
> 
> 
> 
> image
> 
> 

Excellent, thanks for testing, you've been a great help as ever buddy 🙏🏻

**Pull request merged**
