### PR TITLE
Add pnpm support for the project

### PR DESCRIPTION
**Pull request by jamesrweb**
## Proposed Changes

- Add PNPM support for the project to speed up installs, upgrades, etc of dependencies.
- Update workflows to utilise pnpm over npm

## Additional Notes (optional)

You can find [a comparison video](https://youtu.be/d1E31WPR70g) on [their website](https://pnpm.io/) and from my own testing, it is at least 3 times faster than NPM on my machine for administrative tasks related to dependencies.

### CODE REVIEW

**Comment by jamesrweb** [comment]
@yevdyko merged the base branch into this one and resolved the conflicts now. 😄

**Review by yevdyko — APPROVED** [review]
yeah, pnpm is a good thing! the only thing that bothers me is that PR includes changes from the base branch and diff is wrong.

I assume that the CI workflow can be properly tested after the PR is merged.

**Comment by jamesrweb** [comment]
> yeah, pnpm is a good thing! the only thing that bothers me is that PR includes changes from the base branch and diff is wrong.
> 
> I assume that the CI workflow can be properly tested after the PR is merged.

I will merge now and let's see then 😄

**Comment by yevdyko** [comment]
> @yevdyko merged the base branch into this one and resolved the conflicts now. 😄

then it's ready to go 🐎

**Pull request merged**
