### PR TITLE
Update project dependencies

### PR DESCRIPTION
**Pull request by jamesrweb**
- Dependency updates

Auto-generated by [create-pull-request][1]

[1]: https://github.com/peter-evans/create-pull-request

### CODE REVIEW

**Comment by yevdyko** [comment]
@jamesrweb it looks like we have to run the `pnpm format` command before creating a commit, right?

Here is the PR with a fix #187

**Comment by jamesrweb** [comment]
> @jamesrweb it looks like we have to run the `pnpm format` command before creating a commit, right?
> 
> 
> 
> Here is the PR with a fix #187 

Yes, correct, nice catch! 🙏🏻

**Comment by jamesrweb** [comment]
@yevdyko ready for review again.

**Review by yevdyko — APPROVED** [review]
🚢

**Pull request merged**
