### PR TITLE
Update README.md, fix the install command guide.

### PR DESCRIPTION
**Pull request by nooooocato**
Fixes #

## Proposed Changes
If you do not install @types/p5 while installing this package, TypeScript development tools will not provide complete type hints.

## Additional Notes (optional)
It might be better to provide a complete explanation and mention the **--save-dev** option, I'm not sure.

### CODE REVIEW

**Comment by jamesrweb** [comment]
Please run the `format` script and push the formatting fixes.

Please also have the two install steps, one for the dependencies and one for the development dependencies and add an explanation for each as you also recommend yourself ☺️.

Thank you in advance. 👍🏻

**Comment by jamesrweb** [comment]
Closed in favour of #457

**Comment by nooooocato** [comment]
> Please run the `format` script and push the formatting fixes.
> 
> Please also have the two install steps, one for the dependencies and one for the development dependencies and add an explanation for each as you also recommend yourself ☺️.
> 
> Thank you in advance. 👍🏻

Thank you. I'm sorry I saw it so late. I have no experience in open source and don't often read notifications. Anyway, #457 is good to solve it.

**Comment by jamesrweb** [comment]
No need to apologise @nooooocato, thank you so much for the contribution and I hope you do so again in future! ❤️

**Pull request closed without merging**
